Repository tyrxuya/Vibely, pull requests merged in 2025-04, with the labels that each got.

#2 [MA-010] Created entity classes
  .gitignore
  Vibely_App/API/IBusiness.cs
  Vibely_App/API/IGenreBusiness.cs
  Vibely_App/API/IPlaylistBusiness.cs
  Vibely_App/API/IPlaylistSongBusiness.cs
  Vibely_App/API/ISongBusiness.cs
  Vibely_App/API/IUserBusiness.cs
  Vibely_App/API/IUserPlaylistBusiness.cs
  Vibely_App/Business/GenreBusiness.cs
  Vibely_App/Business/PlaylistBusiness.cs
  Vibely_App/Business/PlaylistSongBusiness.cs
  Vibely_App/Business/SongBusiness.cs
  Vibely_App/Business/UserBusiness.cs
  Vibely_App/Business/UserPlaylistBusiness.cs
  Vibely_App/Data/Models/Genre.cs
  Vibely_App/Data/Models/Playlist.cs
  Vibely_App/Data/Models/PlaylistSong.cs
  Vibely_App/Data/Models/Song.cs
  Vibely_App/Data/Models/User.cs
  Vibely_App/Data/Models/UserPlaylist.cs
  Vibely_App/Data/VibelyDbContext.cs
  Vibely_App/Migrations/20250405125856_CreateBaseEntities.Designer.cs
  Vibely_App/Migrations/20250405125856_CreateBaseEntities.cs
  Vibely_App/Migrations/VibelyDbContextModelSnapshot.cs
Labels: enhancement

#3 [MA-009] Implemented Login form
  Vibely_App/API/APIConstants.cs
  Vibely_App/Controls/GradientPanel.cs
  Vibely_App/Controls/GradientPanel.resx
  Vibely_App/Controls/IconHelper.cs
  Vibely_App/Images/Image.cs
  Vibely_App/Properties/Resources.Designer.cs
  Vibely_App/Properties/Resources.resx
  Vibely_App/Resources/VibelyLogo.ico
  Vibely_App/Resources/login.ico
  Vibely_App/Resources/logo.ico
  Vibely_App/Resources/logo.png
  Vibely_App/Resources/password.ico
  Vibely_App/Vibely_App.csproj
  Vibely_App/Vibely_App.sln
  Vibely_App/View/LoginForm.Designer.cs
  Vibely_App/View/LoginForm.cs
  Vibely_App/View/LoginForm.resx
  Vibely_App/View/RegisterForm.Designer.cs
  Vibely_App/View/RegisterForm.cs
  Vibely_App/View/RegisterForm.resx
Labels: bug, enhancement

#4 v0.1 Entities and login form initialization
  .gitignore
  Vibely_App/API/APIConstants.cs
  Vibely_App/API/IBusiness.cs
  Vibely_App/API/IGenreBusiness.cs
  Vibely_App/API/IPlaylistBusiness.cs
  Vibely_App/API/IPlaylistSongBusiness.cs
  Vibely_App/API/ISongBusiness.cs
  Vibely_App/API/IUserBusiness.cs
  Vibely_App/API/IUserPlaylistBusiness.cs
  Vibely_App/Business/GenreBusiness.cs
  Vibely_App/Business/PlaylistBusiness.cs
  Vibely_App/Business/PlaylistSongBusiness.cs
  Vibely_App/Business/SongBusiness.cs
  Vibely_App/Business/UserBusiness.cs
  Vibely_App/Business/UserPlaylistBusiness.cs
  Vibely_App/Controls/GradientPanel.cs
  Vibely_App/Controls/GradientPanel.resx
  Vibely_App/Controls/IconHelper.cs
  Vibely_App/Data/Models/Genre.cs
  Vibely_App/Data/Models/Playlist.cs
  Vibely_App/Data/Models/PlaylistSong.cs
  Vibely_App/Data/Models/Song.cs
  Vibely_App/Data/Models/User.cs
  Vibely_App/Data/Models/UserPlaylist.cs
  Vibely_App/Data/VibelyDbContext.cs
  Vibely_App/Migrations/20250405125856_CreateBaseEntities.Designer.cs
  Vibely_App/Migrations/20250405125856_CreateBaseEntities.cs
  Vibely_App/Migrations/20250412141845_AddedProfilePictureToUser.Designer.cs
  Vibely_App/Migrations/20250412141845_AddedProfilePictureToUser.cs
  Vibely_App/Migrations/VibelyDbContextModelSnapshot.cs
  Vibely_App/Program.cs
  Vibely_App/Properties/Resources.Designer.cs
  Vibely_App/Properties/Resources.resx
  Vibely_App/Resources/VibelyLogo.ico
  Vibely_App/Resources/login.ico
  Vibely_App/Resources/logo.ico
  Vibely_App/Resources/logo.png
  Vibely_App/Resources/password.ico
  Vibely_App/Vibely_App.csproj
  Vibely_App/Vibely_App.sln
  Vibely_App/View/LoginForm.Designer.cs
  Vibely_App/View/LoginForm.cs
  Vibely_App/View/LoginForm.resx
  Vibely_App/View/RegisterForm.Designer.cs
  Vibely_App/View/RegisterForm.cs
  Vibely_App/View/RegisterForm.resx
  Vibely_App_Test/UnitTest1.cs
  Vibely_App_Test/Vibely_App_Test.csproj
Labels: enhancement

#8 [MA-021] Implement Register form
  Vibely_App/Controls/IconHelper.cs
  Vibely_App/View/LoginForm.Designer.cs
  Vibely_App/View/LoginForm.cs
  Vibely_App/View/LoginForm.resx
  Vibely_App/View/RegisterForm.Designer.cs
  Vibely_App/View/RegisterForm.cs
  Vibely_App/View/RegisterForm.resx
Labels: enhancement

#9 [MA-012] Implemented register functionality
  Vibely_App/API/IPasswordHasher.cs
  Vibely_App/API/IUserBusiness.cs
  Vibely_App/Business/PasswordHasher.cs
  Vibely_App/Business/UserBusiness.cs
  Vibely_App/View/RegisterForm.Designer.cs
  Vibely_App/View/RegisterForm.cs
Labels: enhancement

#10 [MA-011] Implemented login functionality
  Vibely_App/API/IUserBusiness.cs
  Vibely_App/Business/UserBusiness.cs
  Vibely_App/View/LoginForm.Designer.cs
  Vibely_App/View/LoginForm.cs
Labels: enhancement

#11 [MA-013] Implement Main form
  Vibely_App/Controls/SongControl.cs
  Vibely_App/Controls/SongControl.resx
  Vibely_App/Vibely_App.csproj
  Vibely_App/View/LoginForm.Designer.cs
  Vibely_App/View/LoginForm.cs
  Vibely_App/View/MainApp.Designer.cs
  Vibely_App/View/MainApp.cs
  Vibely_App/View/MainApp.resx
  Vibely_App/View/RegisterForm.cs
  Vibely_App/View/UIConfigurator.cs
Labels: enhancement

#13 [MA-014] Implement User profile form
  Vibely_App/View/LoginForm.Designer.cs
  Vibely_App/View/LoginForm.cs
  Vibely_App/View/MainApp.cs
  Vibely_App/View/ProfileForm.cs
  Vibely_App/View/ProfileForm.resx
  Vibely_App/View/UIConfigurator.cs
Labels: enhancement

#14 [MA-019] Implement light/dark mode
  Vibely_App/Controls/SongControl.cs
  Vibely_App/View/MainApp.Designer.cs
  Vibely_App/View/MainApp.cs
  Vibely_App/View/MainApp.resx
  Vibely_App/View/ProfileForm.cs
  Vibely_App/View/ProfileForm.resx
  Vibely_App/View/UIConfigurator.cs
Labels: enhancement

#15 [MA-016] Implement add playlist functionality
  Vibely_App/View/ProfileForm.cs
  Vibely_App/View/UIConfigurator.cs
Labels: enhancement

#17 [MA-024] Implement add to playlist functionality
  Vibely_App/API/IPlaylistBusiness.cs
  Vibely_App/API/IPlaylistSongBusiness.cs
  Vibely_App/Business/PlaylistBusiness.cs
  Vibely_App/Business/PlaylistSongBusiness.cs
  Vibely_App/Controls/SongControl.cs
  Vibely_App/View/MainApp.cs
  Vibely_App/View/UIConfigurator.cs
Labels: enhancement

#18 [MA-017] Implement audio playback functionality
  Vibely_App/Data/VibelyDbContext.cs
  Vibely_App/Vibely_App.csproj
  Vibely_App/View/UIConfigurator.cs
Labels: enhancement

#19 [MA-020] Implement search functionality
  Vibely_App/View/UIConfigurator.cs
Labels: enhancement

#20 [MA][hotfix] Fixed playback issue
  Vibely_App/View/UIConfigurator.cs
Labels: bug
